apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wazuh
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./envs/local-env
  prune: true
  sourceRef:
    kind: GitRepository
    name: wazuh
  targetNamespace: wazuh
