apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qaroo
  namespace: kommander-flux 
spec:
  interval: 5m0s
  path: ./envs/local-env
  prune: true
  sourceRef:
    kind: GitRepository
    name: qaroo
  targetNamespace: wazuh
