apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: qaroo
  namespace: kommander-flux 
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/gemku/wazuh-kubernetes.git
